# define a list of properties youd like returned
# be wary though that they may not always return numerical values
# in which case you will get a parsing error in Prometheus
# https://curl.haxx.se/libcurl/c/curl_easy_getinfo.html (skip the CURLINFO_ part)
curl_attributes:
- namelookup_time
- connect_time
- starttransfer_time
- total_time
- response_code
- appconnect_time
- pretransfer_time
- redirect_time
- redirect_count
- size_download
- speed_download
- speed_upload
- request_size
- header_size
- ssl_verifyresult
- os_errno
options:
  port: 10080    # listen port
  max_threads: 4
  curl_debug: True          # print curl exceptions
  webserver_debug: False    # print webserver debugging information
  access_log: False         # print access log
curl_settings:
  # https://curl.haxx.se/libcurl/c/curl_easy_setopt.html
  # do not set url here please :)
  # please respect variable types
  # int  -> int
  # long -> pass a float
  # string -> will be evaluated as property name first, passed as string if not found (ie. for headers)
  opt_certinfo: 1           # get SSL information? (https requests only)
  followlocation: 1         # follow redirects?
  ssl_verifypeer: 0         #
  ssl_verifyhost: 0         #
  connecttimeout: 10        # connect timeout seconds
  timeout: 10               # second timeout for curl functions
  ipresolve: ipresolve_v4   # use ipv4? this maps to CURL_IPRESOLVE_V4
  useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
